# ansible/roles/security/handlers/main.yml
---
- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
