# ansible/roles/security/handlers/main.yml
---
- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
