# ansible/roles/sealed_secrets/tasks/verify.yml
---
- name: Verify Sealed Secrets deployment
  ansible.builtin.shell: |
    kubectl wait --timeout=5m -n {{ sealed_secrets_namespace }} deployment/sealed-secrets --for=condition=Available
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: sealed_secrets_status
  failed_when: sealed_secrets_status.rc != 0
  changed_when: false