"all":
  "children":
    "k3s_servers":
      "hosts":
        "k3s-dev-01": {}
  "hosts":
    "k3s-dev-01":
      "ansible_host": "46.225.138.222"
      "ansible_ssh_private_key_file": "~/.ssh/hetzner_cloud"
      "ansible_user": "deploy"
      "ipv4_address": "46.225.138.222"
      "ipv6_address": "2a01:4f8:c2c:892a::1"
      "ipv6_network": "2a01:4f8:c2c:892a::/64"
      "minio_volume_id": "104659000"
      "mongodb_volume_id": "104659001"
      "server_id": "120832636"
