# ansible/roles/velero/tasks/verify.yml
---
- name: Verify Velero deployment
  ansible.builtin.shell: |
    kubectl wait --timeout=5m -n {{ velero_namespace }} deployment/velero --for=condition=Available
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: velero_status
  failed_when: velero_status.rc != 0
  changed_when: false
