# ansible/roles/k3s_server/tasks/main.yml
---
- name: Install K3s
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags: [k3s, install]

- name: Configure K3s
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/configure.yml"
  tags: [k3s, configure]

- name: Export kubeconfig
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/kubeconfig.yml"
  tags: [k3s, kubeconfig]
